version: '3'

networks:
  workshop_mongo_network:

services:
  mongo:
    image: mongo:latest
    container_name: mongo-workshop_mongo
    environment:
      MONGODB_ADMIN_USER: root
      MONGODB_ADMIN_PASS: root
      MONGO_INITDB_DATABASE: workshop_mongo
   
    ports:
    - 27017:27017
    command: mongod
    networks:
    - workshop_mongo_network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-workshop_mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rccipriano
      ME_CONFIG_BASICAUTH_PASSWORD: rccipriano
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - workshop_mongo_network